# DATASOURCE (Railway MySQL)
spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

server:
  port: ${PORT:8080}

app:
  cors:
    allowed-origins: "*"
  jwt:
    secret: ${JWT_SECRET}

stripe:
  key:
    secret: ${STRIPE_SECRET}

openai:
  api-key: ${OPENAI_KEY}
